displays:
  - name: DVI-D-0
    #workspaces: [1,2,3,4,5,6,7,8,9,0]
    #randr_extra_options: "--left-of DisplayPort-1"
  - name: HDMI-A-0
    #workspaces: [1,2,3,4,5,6,7,8,9,0]
    randr_extra_options: "--left-of DVI-D-0"
  - name: DisplayPort-1
    #workspaces: [1,2,3,4,5,6,7,8,9,0]
    randr_extra_options: "--right-of DVI-D-0 --rotate left"
